var $,surveyComponent='.floating-survey',surveyComponentVisible='floating-survey--visible',surveyComponentHidden='floating-survey--toggle',surveyComponentFirstStep='.floating-survey__first-step',surveyComponentSecondStep='.floating-survey__second-step',surveyButton='.floating-survey__button--survey',customerServiceButton='.floating-survey__button--customer-service',sendCustomerServiceButton='.floating-survey__button--customer-service-send',submittedChatFromSurvey=false;function triggerSurvey(){$(surveyComponent).addClass(surveyComponentVisible);actionSendToCustomerService();actionSendSurvey();surveyHide();surveyClose();Cookies.set('hotjarSurvey',true);}
function showSurveyOnMouseOut(){if(typeof Cookies.get('hotjarSurvey')=='undefined'){setTimeout(function(){$(document).on('mouseout',function(evt){if((evt.toElement===undefined||evt.toElement===null)&&(evt.relatedTarget===undefined||evt.relatedTarget===null)){$(evt.currentTarget).off('mouseout');window.triggerSurvey();}});},8000);}}
function surveyHide(){var hideButton='.floating-survey__close',hideButtonToggle='floating-survey__close--toggle';$(hideButton).on('click',function(e){$(surveyComponent).toggleClass(surveyComponentHidden);$(e.currentTarget).toggleClass(hideButtonToggle);});}
function actionSendSurvey(){var mainBlock='.floating-survey__main',actionsBlock='.floating-survey__actions';$(surveyButton).on('click',function(){$(mainBlock).hide();$(actionsBlock).hide();var theName='anonymous';var theEmail='anonymous@helloprint.com';sendSurvey(theName,theEmail);showThankYouBlock();});}
function sendSurvey(theName,theEmail){var country=window.country_iso.toUpperCase();var text=$('#floating-survey-textarea').val();var subject='Exit intent survey '+country;if(typeof window.analytics!=='undefined'){analytics.track(subject,{survey:subject,message:text,'language':window.lang_iso+'_'+window.country_iso,'countryCode':window.country_iso,'sourceTracking':'segment_old','loginStatus':window.cs_is_loggedin},{context:{page:{url:window.location.href,path:window.location.pathname}}});}}
function sendToDixaWebhook(subject,theName,theEmail,text){var formData=new FormData();formData.append('name',theName)
formData.append('subject',subject);formData.append('email',theEmail);formData.append('message',text);fetch('https://forms.dixa.io/v2/forms/734UO5aJSvUB6t12XJeV1S/wnWMml0UgK7j1x5Yubh2s',{method:'POST',body:formData}).then(r=>r.json())}
function showThankYouBlock(){var thankYouBlock='.floating-survey__thank-you'
$(thankYouBlock).show();}
function actionSendToCustomerService(){$(customerServiceButton).on('click',function(){$(surveyComponentFirstStep).hide();$(surveyButton).hide();$(customerServiceButton).hide();var chatEmail=window.dataCollectionForExperiments.customer_email;var chatName=window.dataCollectionForExperiments.customer_name;if(chatEmail&&chatName&&chatName!==" "){theEmail=chatEmail;theName=chatName;submitToChat(theName,theEmail);}else{$(sendCustomerServiceButton).show();$(surveyComponentSecondStep).show();$(sendCustomerServiceButton).on('click',submitToChatNotLoggedIn);}});}
function submitToChatNotLoggedIn(){var theName,theEmail;if($('#floating-survey-name').val()!==''){theName=$('#floating-survey-name').val();}
if($('#floating-survey-email').val()!==''){theEmail=$('#floating-survey-email').val();}
if(theName&&theEmail){submitToChat(theName,theEmail);$(sendCustomerServiceButton).hide();$(surveyComponentSecondStep).hide();}}
function submitToChat(theName,theEmail){var text=$('#floating-survey-textarea').val();submittedChatFromSurvey=true;var subject='Exit Intent survey '+window.country_iso.toUpperCase()+' into Chat';if(typeof window.analytics!=='undefined'){analytics.track(subject,{survey:subject,message:text,name:theName,email:theEmail,csavailable:window.CSAvailable,'language':window.lang_iso+'_'+window.country_iso,'countryCode':window.country_iso,'sourceTracking':'segment_old','loginStatus':window.cs_is_loggedin},{context:{page:{url:window.location.href,path:window.location.pathname}}});}
if(typeof window.dixa==='undefined'){window.openChat();}
if(typeof window._dixa!=='undefined'){window._dixa("api.setUser",theName,theEmail);window._dixa('api.setView','conversation');window._dixa('api.setUserUrl','https://'+window.location.hostname+'/exitsurvey');setTimeout(function(){window._dixa('api.setMessage',text);},3000);}
$(surveyComponent).hide();$('.chat-facade').hide();}
function surveyClose(){var closeButton='.floating-survey__button--close-survey';$(closeButton).on('click',function(){$(surveyComponent).hide();});}
$(document).ready(function(){if(window.country_iso==='GB'||window.country_iso==='NL'||window.country_iso==='ES'||window.country_iso==='IT'||(window.country_iso==='BE'&&window.lang_iso==='nl')){showSurveyOnMouseOut();}});